# Generated by Django 4.2.24 on 2025-09-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pontos_ranking',
            field=models.IntegerField(default=0, verbose_name='Pontos de Ranking'),
        ),
    ]
