version: '3.8'

services:
  db:
    image: mariadb:11
    container_name: votebem_db_dev
    environment:
      MARIADB_DATABASE: votebem_dev
      MARIADB_USER: votebem_user
      MARIADB_PASSWORD: votebem_dev_password
      MARIADB_ROOT_PASSWORD: votebem_root_pwd
    volumes:
      - mariadb_dev_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$MARIADB_USER -p$MARIADB_PASSWORD || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: votebem_redis_dev
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: votebem_web_dev
    environment:
      - DEBUG=True
      - DATABASE_URL=mysql://votebem_user:votebem_dev_password@db:3306/votebem_dev?charset=utf8mb4
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - SECRET_KEY=dev-secret-key-not-for-production
      - DJANGO_SETTINGS_MODULE=votebem.settings.development
      - ENABLE_REMOTE_DEBUG=True
    volumes:
      - .:/app
      - static_dev_volume:/app/staticfiles
      - media_dev_volume:/app/media
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate --settings=votebem.settings.development &&
             python manage.py collectstatic --noinput --settings=votebem.settings.development &&
             python manage.py runserver 0.0.0.0:8000 --settings=votebem.settings.development"

volumes:
  mariadb_dev_data:
  redis_dev_data:
  static_dev_volume:
  media_dev_volume:

networks:
  default:
    name: vps_dev_network