services:
  # MariaDB Database
  db:
    image: mariadb:11
    container_name: votebem_db_dev
    environment:
      MARIADB_DATABASE: votebem_dev
      MARIADB_USER: votebem_user
      MARIADB_PASSWORD: votebem_dev_password
      MARIADB_ROOT_PASSWORD: votebem_root_pwd
    volumes:
      - mariadb_dev_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$MARIADB_USER -p$MARIADB_PASSWORD || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vps_dev_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: votebem_redis_dev
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vps_dev_network

  # Nginx Reverse Proxy (Optional - for testing production-like setup)
  nginx:
    image: nginx:alpine
    container_name: votebem_nginx_dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/var/www/static:ro
      - ./media:/var/www/media:ro
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - vps_dev_network

  # Adminer (Optional - Database Management UI)
  adminer:
    image: adminer:latest
    container_name: votebem_adminer_dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - vps_dev_network

  # Redis Commander (Optional - Redis Management UI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: votebem_redis_commander_dev
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - vps_dev_network

volumes:
  mariadb_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  # adminer has no volume

networks:
  vps_dev_network:
    driver: bridge