version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: votebem_db_dev
    environment:
      POSTGRES_DB: votebem_dev
      POSTGRES_USER: votebem_user
      POSTGRES_PASSWORD: votebem_dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U votebem_user -d votebem_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: votebem_redis_dev
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: votebem_web_dev
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://votebem_user:votebem_dev_password@db:5432/votebem_dev
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - SECRET_KEY=dev-secret-key-not-for-production
      - DJANGO_SETTINGS_MODULE=votebem.settings.development
      - ENABLE_REMOTE_DEBUG=True
    volumes:
      - .:/app
      - static_dev_volume:/app/staticfiles
      - media_dev_volume:/app/media
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_dev_data:
  redis_dev_data:
  static_dev_volume:
  media_dev_volume:

networks:
  default:
    name: votebem_dev_network