# Generated by Django 4.2.25 on 2025-11-23 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# voting.migrations.0006_proposicao_pk_refactor
# voting.migrations.0008_refactor_to_proposicaovotacao
# voting.migrations.0010_move_official_counts
# voting.migrations.0014_populate_temas
# voting.migrations.0018_voto_integer_peso
# voting.migrations.0021_congressmanvote_voto_codes_data_fix

class Migration(migrations.Migration):

    replaces = [('voting', '0001_initial'), ('voting', '0002_congressman_congressmanvote'), ('voting', '0003_congressman_partidos_historico'), ('voting', '0004_congressmanvote_congress_vote_id'), ('voting', '0005_proposicaovotacao'), ('voting', '0006_proposicao_pk_refactor'), ('voting', '0007_alter_congressmanvote_proposicao_and_more'), ('voting', '0008_refactor_to_proposicaovotacao'), ('voting', '0009_proposicaovotacao_prioridade'), ('voting', '0010_move_official_counts'), ('voting', '0011_votacaovotebem_alter_voto_votacao_and_more'), ('voting', '0012_proposicaovotacao_data_votacao'), ('voting', '0013_tema'), ('voting', '0014_populate_temas'), ('voting', '0015_alter_tema_codigo_proposicaotema'), ('voting', '0016_tema_codigo_primary_key'), ('voting', '0017_alter_proposicaotema_tema_referencia'), ('voting', '0018_voto_integer_peso'), ('voting', '0019_proposicao_data_apresentacao_alter_voto_voto'), ('voting', '0021_congressmanvote_voto_codes_data_fix'), ('voting', '0020_alter_congressmanvote_voto'), ('voting', '0022_merge_20251123_1122'), ('voting', '0022_merge'), ('voting', '0023_merge'), ('voting', '0024_alter_congressmanvote_voto')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proposicao', models.IntegerField(unique=True, verbose_name='ID da Proposição')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('autor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('url_foto1', models.URLField(blank=True, null=True, verbose_name='URL Foto 1')),
                ('alt_foto1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Foto 1')),
                ('url_foto2', models.URLField(blank=True, null=True, verbose_name='URL Foto 2')),
                ('alt_foto2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Foto 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proposição',
                'verbose_name_plural': 'Proposições',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotacaoDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título da Votação')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('data_hora_votacao', models.DateTimeField(verbose_name='Data/Hora da Votação Original')),
                ('no_ar_desde', models.DateTimeField(verbose_name='No Ar Desde')),
                ('no_ar_ate', models.DateTimeField(blank=True, null=True, verbose_name='No Ar Até')),
                ('sim_oficial', models.IntegerField(default=0, verbose_name='Votos SIM Oficiais')),
                ('nao_oficial', models.IntegerField(default=0, verbose_name='Votos NÃO Oficiais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição')),
                ('proposicao_tmp', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Votação Disponível',
                'verbose_name_plural': 'Votações Disponíveis',
                'ordering': ['-no_ar_desde'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('ABSTENCAO', 'Abstenção')], max_length=10, verbose_name='Voto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votacaodisponivel', verbose_name='Votação')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'votacao')},
            },
        ),
        migrations.CreateModel(
            name='Congressman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cadastro', models.IntegerField(unique=True, verbose_name='ID Cadastro')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('partido', models.CharField(max_length=50, verbose_name='Partido')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='URL da Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partidos_historico', models.TextField(blank=True, null=True, verbose_name='Partidos (histórico)')),
            ],
            options={
                'verbose_name': 'Congressista',
                'verbose_name_plural': 'Congressistas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProposicaoVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacao_sufixo', models.IntegerField(verbose_name='ID da Votação (sufixo)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Votação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacoes_oficiais', to='voting.proposicao', verbose_name='Proposição')),
                ('proposicao_tmp', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Votação da Proposição',
                'verbose_name_plural': 'Votações da Proposição',
                'ordering': ['-created_at'],
                'unique_together': {('proposicao', 'votacao_sufixo')},
            },
        ),
        migrations.CreateModel(
            name='CongressmanVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(blank=True, choices=[(1, 'Sim'), (-1, 'Não'), (0, 'Abstenção'), (None, 'Não Compareceu')], null=True, verbose_name='Voto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.congressman', verbose_name='Congressista')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição')),
                ('congress_vote_id', models.IntegerField(blank=True, null=True, verbose_name='ID Votação da Câmara')),
                ('proposicao_tmp', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Voto do Congressista',
                'verbose_name_plural': 'Votos dos Congressistas',
                'ordering': ['-created_at'],
                'unique_together': {('congressman', 'proposicao')},
            },
        ),
        migrations.RunPython(
            code=voting.migrations.0006_proposicao_pk_refactor.fill_tmp_proposicao_ids,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='proposicaovotacao',
            name='proposicao_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voting.proposicao', to_field='id_proposicao', verbose_name='Proposição (nova)'),
        ),
        migrations.AddField(
            model_name='votacaodisponivel',
            name='proposicao_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voting.proposicao', to_field='id_proposicao', verbose_name='Proposição (nova)'),
        ),
        migrations.AddField(
            model_name='congressmanvote',
            name='proposicao_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='voting.proposicao', to_field='id_proposicao', verbose_name='Proposição (nova)'),
        ),
        migrations.RunPython(
            code=voting.migrations.0006_proposicao_pk_refactor.transfer_tmp_to_new_fk,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='proposicaovotacao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='proposicaovotacao',
            name='proposicao',
        ),
        migrations.RemoveField(
            model_name='votacaodisponivel',
            name='proposicao',
        ),
        migrations.AlterUniqueTogether(
            name='congressmanvote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='congressmanvote',
            name='proposicao',
        ),
        migrations.RenameField(
            model_name='proposicaovotacao',
            old_name='proposicao_new',
            new_name='proposicao',
        ),
        migrations.RenameField(
            model_name='votacaodisponivel',
            old_name='proposicao_new',
            new_name='proposicao',
        ),
        migrations.RenameField(
            model_name='congressmanvote',
            old_name='proposicao_new',
            new_name='proposicao',
        ),
        migrations.AlterUniqueTogether(
            name='proposicaovotacao',
            unique_together={('proposicao', 'votacao_sufixo')},
        ),
        migrations.AlterUniqueTogether(
            name='congressmanvote',
            unique_together={('congressman', 'proposicao')},
        ),
        migrations.RemoveField(
            model_name='proposicaovotacao',
            name='proposicao_tmp',
        ),
        migrations.RemoveField(
            model_name='votacaodisponivel',
            name='proposicao_tmp',
        ),
        migrations.RemoveField(
            model_name='congressmanvote',
            name='proposicao_tmp',
        ),
        migrations.AlterField(
            model_name='proposicao',
            name='id_proposicao',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID da Proposição'),
        ),
        migrations.RemoveField(
            model_name='proposicao',
            name='id',
        ),
        migrations.AlterField(
            model_name='congressmanvote',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição'),
        ),
        migrations.AlterField(
            model_name='proposicaovotacao',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacoes_oficiais', to='voting.proposicao', verbose_name='Proposição'),
        ),
        migrations.AlterField(
            model_name='votacaodisponivel',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição'),
        ),
        migrations.AddField(
            model_name='congressmanvote',
            name='proposicao_votacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.proposicaovotacao', verbose_name='Votação da Proposição'),
        ),
        migrations.AddField(
            model_name='votacaodisponivel',
            name='proposicao_votacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.proposicaovotacao', verbose_name='Votação da Proposição'),
        ),
        migrations.RunPython(
            code=voting.migrations.0008_refactor_to_proposicaovotacao.populate_cv_pv,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterUniqueTogether(
            name='congressmanvote',
            unique_together={('congressman', 'proposicao_votacao')},
        ),
        migrations.RemoveField(
            model_name='congressmanvote',
            name='congress_vote_id',
        ),
        migrations.RemoveField(
            model_name='congressmanvote',
            name='proposicao',
        ),
        migrations.RemoveField(
            model_name='votacaodisponivel',
            name='proposicao',
        ),
        migrations.AddField(
            model_name='proposicaovotacao',
            name='prioridade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='proposicaovotacao',
            name='sim_oficial',
            field=models.IntegerField(default=0, verbose_name='Votos SIM Oficiais'),
        ),
        migrations.AddField(
            model_name='proposicaovotacao',
            name='nao_oficial',
            field=models.IntegerField(default=0, verbose_name='Votos NÃO Oficiais'),
        ),
        migrations.RunPython(
            code=voting.migrations.0010_move_official_counts.copy_counts_to_proposicao_votacao,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name='VotacaoVoteBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título da Votação')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('data_hora_votacao', models.DateTimeField(verbose_name='Data/Hora da Votação Original')),
                ('no_ar_desde', models.DateTimeField(verbose_name='No Ar Desde')),
                ('no_ar_ate', models.DateTimeField(blank=True, null=True, verbose_name='No Ar Até')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao_votacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votacaovotebem', to='voting.proposicaovotacao', verbose_name='Votação da Proposição')),
            ],
            options={
                'verbose_name': 'Votação VoteBem',
                'verbose_name_plural': 'Votações VoteBem',
                'ordering': ['-no_ar_desde'],
            },
        ),
        migrations.AlterField(
            model_name='voto',
            name='votacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='voting.votacaovotebem', verbose_name='Votação'),
        ),
        migrations.DeleteModel(
            name='VotacaoDisponivel',
        ),
        migrations.AddField(
            model_name='proposicaovotacao',
            name='data_votacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Registro da Votação'),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(db_index=True)),
                ('nome', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'voting_temas',
            },
        ),
        migrations.RunPython(
            code=voting.migrations.0014_populate_temas.seed_temas,
            reverse_code=voting.migrations.0014_populate_temas.unseed_temas,
        ),
        migrations.AlterField(
            model_name='tema',
            name='codigo',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tema',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='tema',
            name='id',
        ),
        migrations.CreateModel(
            name='ProposicaoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposicao', models.ForeignKey(db_column='proposicao_id', on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição')),
                ('tema', models.ForeignKey(db_column='tema_id', on_delete=django.db.models.deletion.CASCADE, to='voting.tema', verbose_name='Tema (código)')),
            ],
            options={
                'verbose_name': 'Proposição-Tema',
                'verbose_name_plural': 'Proposições-Temas',
                'db_table': 'voting_proposicao_tema',
                'unique_together': {('proposicao', 'tema')},
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL da Referência')),
                ('kind', models.CharField(choices=[('web_page', 'Página Web'), ('sound', 'Áudio'), ('social_media', 'Rede Social')], max_length=20, verbose_name='Tipo da Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao_votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='voting.proposicaovotacao', verbose_name='Votação da Proposição')),
            ],
            options={
                'verbose_name': 'Referência de Votação',
                'verbose_name_plural': 'Referências de Votação',
                'db_table': 'voting_referencias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['proposicao_votacao'], name='voting_refe_proposi_2d1a3d_idx'), models.Index(fields=['kind'], name='voting_refe_kind_fa9889_idx')],
            },
        ),
        migrations.AddField(
            model_name='voto',
            name='peso',
            field=models.SmallIntegerField(default=1, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='voto',
            name='voto_new',
            field=models.IntegerField(choices=[(1, 'Sim'), (-1, 'Não'), (0, 'Abstenção')], null=True, verbose_name='Voto'),
        ),
        migrations.RunPython(
            code=voting.migrations.0018_voto_integer_peso.migrate_voto_char_to_int,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='voto',
            name='voto',
        ),
        migrations.RenameField(
            model_name='voto',
            old_name='voto_new',
            new_name='voto',
        ),
        migrations.AddField(
            model_name='proposicao',
            name='data_apresentacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Apresentação'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='voto',
            field=models.IntegerField(choices=[(1, 'Sim'), (-1, 'Não'), (0, 'Abstenção')], verbose_name='Voto'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=voting.migrations.0021_congressmanvote_voto_codes_data_fix.convert_non_dummy_absence,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='congressmanvote',
            name='voto',
            field=models.IntegerField(choices=[(1, 'Sim'), (-1, 'Não'), (0, 'Abstenção'), (2, 'Não Compareceu')], default=2, verbose_name='Voto'),
        ),
        migrations.AlterField(
            model_name='congressmanvote',
            name='voto',
            field=models.IntegerField(choices=[(1, 'Sim'), (-1, 'Não'), (0, 'Abstenção'), (2, 'Dummy'), (3, 'Não Compareceu'), (4, 'Abstenção (Art. 17)')], default=3, verbose_name='Voto'),
        ),
    ]
