# Generated by Django 4.2.25 on 2025-11-29 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Congressman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cadastro', models.IntegerField(unique=True, verbose_name='ID Cadastro')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('partido', models.CharField(max_length=50, verbose_name='Partido')),
                ('partidos_historico', models.TextField(blank=True, null=True, verbose_name='Partidos (histórico)')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='URL da Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Congressista',
                'verbose_name_plural': 'Congressistas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id_proposicao', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID da Proposição')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('data_apresentacao', models.DateField(blank=True, null=True, verbose_name='Data de Apresentação')),
                ('autor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('url_foto1', models.URLField(blank=True, null=True, verbose_name='URL Foto 1')),
                ('alt_foto1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Foto 1')),
                ('url_foto2', models.URLField(blank=True, null=True, verbose_name='URL Foto 2')),
                ('alt_foto2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Foto 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proposição',
                'verbose_name_plural': 'Proposições',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposicaoVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacao_sufixo', models.IntegerField(verbose_name='ID da Votação (sufixo)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Votação')),
                ('prioridade', models.IntegerField(blank=True, null=True, verbose_name='Prioridade')),
                ('sim_oficial', models.IntegerField(default=0, verbose_name='Votos SIM Oficiais')),
                ('nao_oficial', models.IntegerField(default=0, verbose_name='Votos NÃO Oficiais')),
                ('data_votacao', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Registro da Votação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacoes_oficiais', to='voting.proposicao', verbose_name='Proposição')),
            ],
            options={
                'verbose_name': 'Votação da Proposição',
                'verbose_name_plural': 'Votações da Proposição',
                'ordering': ['-created_at'],
                'unique_together': {('proposicao', 'votacao_sufixo')},
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'voting_temas',
            },
        ),
        migrations.CreateModel(
            name='VotacaoVoteBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título da Votação')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('data_hora_votacao', models.DateTimeField(verbose_name='Data/Hora da Votação Original')),
                ('no_ar_desde', models.DateTimeField(verbose_name='No Ar Desde')),
                ('no_ar_ate', models.DateTimeField(blank=True, null=True, verbose_name='No Ar Até')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao_votacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votacaovotebem', to='voting.proposicaovotacao', verbose_name='Votação da Proposição')),
            ],
            options={
                'verbose_name': 'Votação VoteBem',
                'verbose_name_plural': 'Votações VoteBem',
                'ordering': ['-no_ar_desde'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(choices=[(1, 'Sim'), (-1, 'Não'), (0, 'Abstenção')], verbose_name='Voto')),
                ('peso', models.SmallIntegerField(default=1, verbose_name='Peso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='voting.votacaovotebem', verbose_name='Votação')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'votacao')},
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL da Referência')),
                ('kind', models.CharField(choices=[('web_page', 'Página Web'), ('sound', 'Áudio'), ('social_media', 'Rede Social')], max_length=20, verbose_name='Tipo da Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao_votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='voting.proposicaovotacao', verbose_name='Votação da Proposição')),
            ],
            options={
                'verbose_name': 'Referência de Votação',
                'verbose_name_plural': 'Referências de Votação',
                'db_table': 'voting_referencias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['proposicao_votacao'], name='voting_refe_proposi_2d1a3d_idx'), models.Index(fields=['kind'], name='voting_refe_kind_fa9889_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProposicaoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposicao', models.ForeignKey(db_column='proposicao_id', on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição')),
                ('tema', models.ForeignKey(db_column='tema_id', on_delete=django.db.models.deletion.CASCADE, to='voting.tema', verbose_name='Tema (código)')),
            ],
            options={
                'verbose_name': 'Proposição-Tema',
                'verbose_name_plural': 'Proposições-Temas',
                'db_table': 'voting_proposicao_tema',
                'unique_together': {('proposicao', 'tema')},
            },
        ),
        migrations.CreateModel(
            name='CongressmanVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(choices=[(1, 'Sim'), (-1, 'Não'), (0, 'Abstenção'), (2, 'Dummy'), (3, 'Não Compareceu'), (4, 'Abstenção (Art. 17)')], default=3, verbose_name='Voto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.congressman', verbose_name='Congressista')),
                ('proposicao_votacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.proposicaovotacao', verbose_name='Votação da Proposição')),
            ],
            options={
                'verbose_name': 'Voto do Congressista',
                'verbose_name_plural': 'Votos dos Congressistas',
                'ordering': ['-created_at'],
                'unique_together': {('congressman', 'proposicao_votacao')},
            },
        ),
    ]
