# Generated by Django 4.2.23 on 2025-08-07 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proposicao', models.IntegerField(unique=True, verbose_name='ID da Proposição')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('autor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('url_foto1', models.URLField(blank=True, null=True, verbose_name='URL Foto 1')),
                ('alt_foto1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Foto 1')),
                ('url_foto2', models.URLField(blank=True, null=True, verbose_name='URL Foto 2')),
                ('alt_foto2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Foto 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proposição',
                'verbose_name_plural': 'Proposições',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotacaoDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título da Votação')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('data_hora_votacao', models.DateTimeField(verbose_name='Data/Hora da Votação Original')),
                ('no_ar_desde', models.DateTimeField(verbose_name='No Ar Desde')),
                ('no_ar_ate', models.DateTimeField(blank=True, null=True, verbose_name='No Ar Até')),
                ('sim_oficial', models.IntegerField(default=0, verbose_name='Votos SIM Oficiais')),
                ('nao_oficial', models.IntegerField(default=0, verbose_name='Votos NÃO Oficiais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição')),
            ],
            options={
                'verbose_name': 'Votação Disponível',
                'verbose_name_plural': 'Votações Disponíveis',
                'ordering': ['-no_ar_desde'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('ABSTENCAO', 'Abstenção')], max_length=10, verbose_name='Voto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.votacaodisponivel', verbose_name='Votação')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'votacao')},
            },
        ),
    ]
