# Generated by Django 4.2.25 on 2025-12-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Palavras-chave'),
        ),
        migrations.AddField(
            model_name='votacaovotebem',
            name='explicacao',
            field=models.TextField(blank=True, null=True, verbose_name='Explicação'),
        ),
    ]
