# Generated by Django 4.2.23 on 2025-09-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congressman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cadastro', models.IntegerField(unique=True, verbose_name='ID Cadastro')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('partido', models.CharField(max_length=50, verbose_name='Partido')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='URL da Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Congressista',
                'verbose_name_plural': 'Congressistas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CongressmanVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.IntegerField(blank=True, choices=[(1, 'Sim'), (-1, 'Não'), (0, 'Abstenção'), (None, 'Não Compareceu')], null=True, verbose_name='Voto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('congressman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.congressman', verbose_name='Congressista')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição')),
            ],
            options={
                'verbose_name': 'Voto do Congressista',
                'verbose_name_plural': 'Votos dos Congressistas',
                'ordering': ['-created_at'],
                'unique_together': {('congressman', 'proposicao')},
            },
        ),
    ]
