# Generated by Django 4.2.23 on 2025-10-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_congressman_congressmanvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressman',
            name='partidos_historico',
            field=models.TextField(blank=True, null=True, verbose_name='Partidos (histórico)'),
        ),
    ]
