# Generated by Django 4.2.25 on 2025-12-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_proposicao_keywords_votacaovotebem_explicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='conhecida_por',
            field=models.TextField(blank=True, null=True, verbose_name='Conhecida por'),
        ),
    ]
