# Generated by Django 4.2.25 on 2025-12-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_proposicao_conhecida_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicao',
            name='titulo',
            field=models.TextField(verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='kind',
            field=models.CharField(choices=[('web_page', 'Página Web'), ('sound', 'Áudio'), ('social_media', 'Vídeo no YouTube')], max_length=20, verbose_name='Tipo da Referência'),
        ),
        migrations.AlterField(
            model_name='votacaovotebem',
            name='titulo',
            field=models.TextField(verbose_name='Título da Votação'),
        ),
    ]
