# Generated by Django 4.2.25 on 2025-11-12 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_congressmanvote_congress_vote_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposicaoVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votacao_sufixo', models.IntegerField(verbose_name='ID da Votação (sufixo)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Votação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacoes_oficiais', to='voting.proposicao', verbose_name='Proposição')),
            ],
            options={
                'verbose_name': 'Votação da Proposição',
                'verbose_name_plural': 'Votações da Proposição',
                'ordering': ['-created_at'],
                'unique_together': {('proposicao', 'votacao_sufixo')},
            },
        ),
    ]
