# Generated by Django 4.2.27 on 2026-01-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_extend_referencias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votacaovotebem',
            options={'ordering': ['sort_order', '-no_ar_desde'], 'verbose_name': 'Votação VoteBem', 'verbose_name_plural': 'Votações VoteBem'},
        ),
        migrations.AddField(
            model_name='votacaovotebem',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ordem de Exibição'),
        ),
    ]
