# Generated by Django 4.2.25 on 2025-11-12 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_proposicao_pk_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressmanvote',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição'),
        ),
        migrations.AlterField(
            model_name='proposicaovotacao',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacoes_oficiais', to='voting.proposicao', verbose_name='Proposição'),
        ),
        migrations.AlterField(
            model_name='votacaodisponivel',
            name='proposicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição'),
        ),
    ]
