# Generated by Django 4.2 on 2025-11-13

from django.db import migrations, models
import django.db.models.deletion


def populate_cv_pv(apps, schema_editor):
    CongressmanVote = apps.get_model('voting', 'CongressmanVote')
    ProposicaoVotacao = apps.get_model('voting', 'ProposicaoVotacao')
    # Map existing congressman votes to a specific ProposicaoVotacao using congress_vote_id
    try:
        for cv in CongressmanVote.objects.all():
            # Access raw fields via *_id to avoid loading relations unnecessarily
            prop_id = getattr(cv, 'proposicao_id', None)
            suffix = getattr(cv, 'congress_vote_id', None)
            if prop_id is None or suffix is None:
                continue
            pv, _ = ProposicaoVotacao.objects.get_or_create(
                proposicao_id=prop_id,
                votacao_sufixo=suffix,
                defaults={'descricao': ''}
            )
            setattr(cv, 'proposicao_votacao_id', pv.id)
            cv.save(update_fields=['proposicao_votacao'])
    except Exception:
        # Best-effort; if anything fails, continue without blocking migration
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_congressmanvote_proposicao_and_more'),
    ]

    operations = [
        # Add new FK fields (nullable) pointing to ProposicaoVotacao
        migrations.AddField(
            model_name='congressmanvote',
            name='proposicao_votacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.proposicaovotacao', verbose_name='Votação da Proposição'),
        ),
        migrations.AddField(
            model_name='votacaodisponivel',
            name='proposicao_votacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.proposicaovotacao', verbose_name='Votação da Proposição'),
        ),

        # Populate CongressmanVote.proposicao_votacao using existing data
        migrations.RunPython(populate_cv_pv, reverse_code=migrations.RunPython.noop),

        # Update unique constraint to be based on (congressman, proposicao_votacao)
        migrations.AlterUniqueTogether(
            name='congressmanvote',
            unique_together={('congressman', 'proposicao_votacao')},
        ),

        # Remove deprecated fields
        migrations.RemoveField(
            model_name='congressmanvote',
            name='congress_vote_id',
        ),
        migrations.RemoveField(
            model_name='congressmanvote',
            name='proposicao',
        ),
        migrations.RemoveField(
            model_name='votacaodisponivel',
            name='proposicao',
        ),
    ]