# Generated by Django 4.2.27 on 2026-01-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_votacaovotebem_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='referencia',
                    name='title',
                    field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Título'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='referencia',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Título'),
        ),
    ]
