# Generated by Django 4.2.25 on 2025-11-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_refactor_to_proposicaovotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicaovotacao',
            name='prioridade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prioridade'),
        ),
    ]
