# Generated by Django 4.2.27 on 2026-03-11 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_alter_divulgador_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='congressman',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='divulgador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.divulgador', verbose_name='Divulgador'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='votacao_votebem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.votacaovotebem', verbose_name='Votação VoteBem'),
        ),
        migrations.AlterField(
            model_name='divulgador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='referencia',
            index=models.Index(fields=['divulgador'], name='voting_refe_divulga_a0eba4_idx'),
        ),
        migrations.AddIndex(
            model_name='referencia',
            index=models.Index(fields=['votacao_votebem'], name='voting_refe_votacao_bbf281_idx'),
        ),
    ]
