# Generated by Django 4.2.25 on 2025-11-13 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_move_official_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotacaoVoteBem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título da Votação')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('data_hora_votacao', models.DateTimeField(verbose_name='Data/Hora da Votação Original')),
                ('no_ar_desde', models.DateTimeField(verbose_name='No Ar Desde')),
                ('no_ar_ate', models.DateTimeField(blank=True, null=True, verbose_name='No Ar Até')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao_votacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votacaovotebem', to='voting.proposicaovotacao', verbose_name='Votação da Proposição')),
            ],
            options={
                'verbose_name': 'Votação VoteBem',
                'verbose_name_plural': 'Votações VoteBem',
                'ordering': ['-no_ar_desde'],
            },
        ),
        migrations.AlterField(
            model_name='voto',
            name='votacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='voting.votacaovotebem', verbose_name='Votação'),
        ),
        migrations.DeleteModel(
            name='VotacaoDisponivel',
        ),
    ]
