# Generated by Django 4.2.23 on 2025-11-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_proposicaovotacao_data_votacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(db_index=True)),
                ('nome', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'voting_temas',
            },
        ),
    ]
