# Generated by Django 4.2.23 on 2025-11-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_populate_temas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='codigo',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProposicaoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposicao', models.ForeignKey(db_column='proposicao_id', on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição')),
                ('tema', models.ForeignKey(db_column='tema_id', on_delete=django.db.models.deletion.CASCADE, to='voting.tema', to_field='codigo', verbose_name='Tema (código)')),
            ],
            options={
                'verbose_name': 'Proposição-Tema',
                'verbose_name_plural': 'Proposições-Temas',
                'db_table': 'voting_proposicao_tema',
                'unique_together': {('proposicao', 'tema')},
            },
        ),
    ]
