# Generated by Django 4.2.25 on 2025-11-15 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_tema_codigo_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposicaotema',
            name='tema',
            field=models.ForeignKey(db_column='tema_id', on_delete=django.db.models.deletion.CASCADE, to='voting.tema', verbose_name='Tema (código)'),
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL da Referência')),
                ('kind', models.CharField(choices=[('web_page', 'Página Web'), ('sound', 'Áudio'), ('social_media', 'Rede Social')], max_length=20, verbose_name='Tipo da Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposicao_votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='voting.proposicaovotacao', verbose_name='Votação da Proposição')),
            ],
            options={
                'verbose_name': 'Referência de Votação',
                'verbose_name_plural': 'Referências de Votação',
                'db_table': 'voting_referencias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['proposicao_votacao'], name='voting_refe_proposi_2d1a3d_idx'), models.Index(fields=['kind'], name='voting_refe_kind_fa9889_idx')],
            },
        ),
    ]
