# Generated by Django 4.2.25 on 2025-11-21 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_voto_integer_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposicao',
            name='data_apresentacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Apresentação'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='voto',
            field=models.IntegerField(choices=[(1, 'Sim'), (-1, 'Não'), (0, 'Abstenção')], verbose_name='Voto'),
            preserve_default=False,
        ),
    ]
