# Generated by Django 4.2.25 on 2025-11-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_proposicao_data_apresentacao_alter_voto_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressmanvote',
            name='voto',
            field=models.IntegerField(choices=[(1, 'Sim'), (-1, 'Não'), (0, 'Abstenção'), (2, 'Não Compareceu')], default=2, verbose_name='Voto'),
        ),
    ]
