# Generated by Django 4.2.25 on 2025-11-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0020_alter_congressmanvote_voto'),
        ('voting', '0021_congressmanvote_voto_codes_data_fix'),
    ]

    operations = [
    ]
