# Generated by Django 4.2.25 on 2025-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0023_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='congressmanvote',
            name='voto',
            field=models.IntegerField(choices=[(1, 'Sim'), (-1, 'Não'), (0, 'Abstenção'), (2, 'Dummy'), (3, 'Não Compareceu'), (4, 'Abstenção (Art. 17)')], default=3, verbose_name='Voto'),
        ),
    ]
