# Generated by Django 4.2.23 on 2025-08-07 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('estado', models.IntegerField(choices=[(5, 'Rascunho'), (10, 'Publicada'), (15, 'Arquivada')], default=5, verbose_name='Estado')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('proposicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição')),
            ],
            options={
                'verbose_name': 'Enquete',
                'verbose_name_plural': 'Enquetes',
                'ordering': ['estado', 'criada_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NEUTRO', 'Neutro')], max_length=10, verbose_name='Resposta')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.enquete', verbose_name='Enquete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resposta da Enquete',
                'verbose_name_plural': 'Respostas das Enquetes',
                'ordering': ['-created_at'],
                'unique_together': {('enquete', 'user')},
            },
        ),
    ]
