# Generated by Django 4.2.25 on 2025-11-12 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_congressmanvote_proposicao_and_more'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='proposicao',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='voting.proposicao', verbose_name='Proposição'),
        ),
    ]
