# Generated by Django 4.2.25 on 2025-11-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_enquete_proposicao'),
        ('polls', '0002_enquete_fk_to_id_proposicao'),
    ]

    operations = [
    ]
